### ISSUE TITLE
citing the package

### ISSUE THREAD

**Issue by OlenaShcherbakova** [Joseph-Watts/BEPA#1]
Hi Joseph!

I know that the package is in beta version and not published yet, but I wanted to double check with you the right way of citing it if I end up using it in my own code.

Does the following (in particular, the year which I am not certain about) sound good to you?
Watts, Joseph. 2022. Brute-force Exploratory Path Analysis in R. https://github.com/Joseph-Watts/BEPA

Thanks for your efforts of helping to generate all possible models! :)

**Comment by Joseph-Watts** [comment]
Hi Olena,

Thanks very much for the question, that citation should be fine thanks. If it is easier, you could also cite the following paper: 

Watts, J., Hamerslag, E., Sprules, C., & Dunbar, R. (2022). Food storage facilitated the emergence of hunter-gatherer professional religious specialists. Evolutionary Human Sciences, 4. https://doi.org/10.1017/ehs.2022.17 

All the best,
Joseph
